apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  background: "https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80"
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com/
              description: The front page of the internet
        - Wykop:
            - href: https://wykop.pl/
              description: Glupie Obrazki

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    - Services:
        - PiHole:
            icon: pi-hole.png
            href: "https://pihole.entropymaker.com/admin"
            description: DNS Ad Blocker
        - Grafana:
            icon: grafana.png
            href: "https://grafana.entropymaker.com"
            description: Metrics
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: "https://jellyfin.entropymaker.com"
            description: Media platform
        - Sonarr: 
            icon: sonarr.png
            href: "https://sonarr.entropymaker.com"
            description: TV Show Search
        - Prowlarr:
            icon: prowlarr.png
            href: "https://prowlarr.entropymaker.com"
            description: TV Show Search
        - Radarr:
            icon: radarr.png
            href: "https://radarr.entropymaker.com/"
            description: Movies Search
        - QBitTorrent:
            icon: qbittorrent.png
            href: "https://qbittorrent.entropymaker.com/"
            description: Torrent Downloads
    - Tools:
        - Longhorn:
            icon: longhorn.png
            href: "https://longhorn.entropymaker.com"
            description: Cluster Block Storage
        - N8n:
            icon: n8n.png
            href: "https://n8n.entropymaker.com"
            description: Automation
        - Unmanic:
            icon: unmanic.png
            href: "https://unmanic.entropymaker.com"
            description: Video Transcoding

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
    
    - openmeteo:
        label: Current
        latitude: 50.088079
        longitude: 19.930431
        cache: 5
        units: metric
  docker.yaml: ""