apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdarr-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - tdarr.entropymaker.com
      secretName: entropymaker-com-tls
  rules:
    - host: tdarr.entropymaker.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: tdarr
                port:
                  number: 8265
