apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

helmCharts:
  - name: tdarr
    repo: https://vhdirk.github.io/helm-charts
    releaseName: tdarr
    namespace: servarr
    version: "5.0.5"
    valuesFile: values.yaml
