image:
  repository: ghcr.io/haveagitgat/tdarr
  tag: 2.33.01

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: tdarr.entropymaker.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tdarr.entropymaker.com"
        secretName: entropymaker-com-tls

persistance:
  config:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: longhorn
    size: 2Gi
    retain: true
  media:
    enabled: true
    existingClaim: servarr-jellyfin-media

node:
  image:
    repository: ghcr.io/haveagitgat/tdarr_node
    tag: 2.33.01
