apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com/
    releaseName: open-webui
    namespace: llm
    version: "6.4.0"
    valuesFile: values.yaml

resources:
  - ./ns.yaml
