ollama:
  enabled: true

persistence:
  enabled: true
  storageClass: "longhorn" # Change based on your storage class
  size: 100G

ingress:
  enabled: true
  class: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: "ollama.entropymaker.com"
  tls: true
  existingSecret: entropymaker-com-tls
