kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: servarr-jellyfin-media
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: media-pv-nfs
  storageClassName: nfs-csi-retain
