apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unmanic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://vhdirk.github.io/helm-charts"
    targetRevision: "0.1.4"
    chart: "unmanic"
    helm:
      releaseName: unmanic
      values: |
        image:
          tag: "0.2.7"

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - host: unmanic.entropymaker.com
                paths:
                  - path: /
                    service:
                      name: unmanic
                      port: 8888
            tls:
              - hosts:
                  - unmanic.entropymaker.com
                secretName: entropymaker-com-tls

        persistence:
          config:
            enabled: true
            storageClass: longhorn
            accessMode: ReadWriteOnce
          library:
            enabled: true
            existingClaim: servarr-jellyfin-media
          cache:
            enabled: true
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 5Gi

  destination:
    server: "https://kubernetes.default.svc" # or your cluster API URL
    namespace: servarr # where you want unmanic deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
