apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: unmanic
    repo: https://vhdirk.github.io/helm-charts
    releaseName: unmanic
    namespace: unmanic
    version: "0.1.4"
    valuesFile: values.yaml
