image:
  tag: "0.2.8"
  repository: josh5/unmanic
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: unmanic.entropymaker.com
        paths:
          - path: /
            service:
              name: unmanic
              port: 8888
    tls:
      - hosts:
          - unmanic.entropymaker.com
        secretName: entropymaker-com-tls
persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
  library:
    enabled: true
    existingClaim: servarr-jellyfin-media
  cache:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 5Gi
