apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack

resources:
  - ./ns.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-stack
    namespace: prometheus-stack
    includeCRDs: true
    version: "69.3.3"
    valuesFile: ./prom-stack-values.yaml
