apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-stack
    namespace: prometheus-stack
    version: "68.5.0"
    valuesFile: ./prom-stack-values.yaml
