apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-stack
    namespace: prometheus-stack
    version: "69.3.1"
    valuesFile: ./prom-stack-values.yaml
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: loki
    version: "6.27.0"
    valuesFile: ./loki-values.yaml
