crds:
  upgradeJob:
    enabled: true

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

    hosts:
      - grafana.entropymaker.com
    path: /
    tls:
      - hosts:
          - grafana.entropymaker.com
        secretName: entropymaker-com-tls
