apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

helmCharts:
  - name: n8n
    repo: oci://8gears.container-registry.com/library
    releaseName: n8n
    namespace: n8n
    version: "1.0.1"
    valuesFile: values.yaml

resources:
  - ./ns.yaml
  - ./ingress.yaml
