serviceDns:
  loadBalancerIP: 192.168.1.222
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - pihole.entropymaker.com
  path: /
  tls:
    - hosts:
        - pihole.entropymaker.com
      secretName: entropymaker-com-tls
persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"
  size: "2Gi"
  accessModes:
    - ReadWriteMany
